Added initial playwright configuration
layer5labs/meshmap-snapshot pull request #49
Opened 2023-09-04 06:01 UTC by VaibhavMalik4187

- Added basic playwright configuration in the playwright-action directory.
- Created a new playwright workflow to run playwright tests.

**Notes for Reviewers**

This PR fixes #

- [X] Yes, I signed my commits.

2023-09-04 06:21 UTC, VaibhavMalik4187 commented
@leecalcote Let's prototype the Playwright configuration here.

2023-09-06 19:02 UTC, VaibhavMalik4187 commented
The situation is very dicey here. Tests are randomly passing and failing. In the last CI run, every single test passed in the runner. All of them failed when I ran `npx playwright test` locally right after pushing the code.
![image](https://github.com/layer5labs/meshmap-snapshot/assets/34866732/5e65112c-465b-43a3-80c4-ef8aa77c5e02)

2023-09-08 10:53 UTC, leecalcote commented on .github/workflows/playwright.yml
> +    branches: [main, master]
We don’t use main.

2023-09-08 10:54 UTC, leecalcote commented on .github/workflows/playwright.yml
> +      - name: Install dependencies
Are there no playwright github actions?

2023-09-08 10:58 UTC, leecalcote requested changes

2023-09-08 10:58 UTC, leecalcote commented on .github/workflows/playwright.yml
> +          retention-days: 1
Will need a bump up.

2023-09-08 10:58 UTC, leecalcote commented on .github/workflows/playwright.yml
> +    timeout-minutes: 10
Not necessary and will only inevitably need a bump up.

2023-09-08 10:58 UTC, leecalcote commented on playwright-action/playwright.config.js
> +      name: "firefox",
Replace with Safari

2023-09-08 10:58 UTC, leecalcote commented on playwright-action/tests/playground.spec.js
> +  await expect(page).toHaveTitle(
This sort of thing is too fragile.

2023-09-11 01:51 UTC, leecalcote approved these changes

2023-09-11 01:51 UTC, merged